### ISSUE TITLE
Is `lengthInLines` really logarithmic time for ropes?

### ISSUE THREAD

**Issue by michaelpj** [Bodigrim/text-rope#1]
Maybe it is, if `lastChar` is logarithmic. It seems a shame, since we have most of the information to hand in constant time.

**Comment by Bodigrim** [comment]
Yes, that's because of `lastChar`, which is needed to reproduce the peculiar semantics of `Data.Text.lines` / `Data.List.lines`. However, if you do not care about this peculiarity, `posLine . lengthAsPosition` works in constant time for ropes.
