### ISSUE TITLE
Reverse rope to navigate backwards from specific position

### ISSUE THREAD

**Issue by VeryMilkyJoe** [Bodigrim/text-rope#2]
Hello, 

I would like to navigate some file contents backwards from a specific position and want to therefore use `splitAtPosition` and then reverse the first part of the return value, is there an efficient way to do this using Ropes and without having to convert back to Text? 

What I was using previously in Text was: `reverse $ take lineposition bigFileContents`.

**Comment by Bodigrim** [comment]
Reversing `Text` is a linear operation anyways, because you need to reverse each individual underlying chunk of a rope. I think what you are doing now is alright.

**Comment by VeryMilkyJoe** [comment]
Great, thank you for the quick response!
